spring:
  application:
    name: theme-service
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    discovery:
      client:
        simple:
          enabled: false # Отключаем простой клиент Spring Cloud Discovery
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/ # URL вашего Eureka сервера
        register-with-eureka: true # Регистрация приложения в Eureka
        fetch-registry: true # Загрузка регистра из Eureka
      instance:
        prefer-ip-address: true # Использовать IP-адрес для регистрации (опционально)
        metadata-map:
          name: theme-service # Имя клиента, которое будет использоваться в Eureka
