spring:
  application:
    name: Theme-service

  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ??? ?????? ????????, ????????, 'validate', 'create', 'create-drop'
    show-sql: true  # ??????????? SQL-????????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect